# Default Flutter template
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false

# Setting RAM untuk Gradle & Kotlin Daemon
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
kotlin.daemon.jvmargs=-Xmx1536m
org.gradle.daemon=false

# Fix untuk error "Could not close incremental caches"
# Penyebab: proyek di D:\ dan cache Pub di C:\ (drive conflict)
# Tanggal: 2026-09-30
# MASALAH BERAKHIR SETELAH BERHARI HARI DENGAN SATU BARIS KODE INI
kotlin.incremental=false

android.enableJetifier=true